name: Test Secret Length

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Check secret is set and print its length
        run: |
          secret="${{ secrets.QA_PASSWORD }}"
          if [ -z "$secret" ]; then
            echo "Secret is missing or empty."
            exit 1
          else
            echo "✅ Secret is set."
            echo "🔒 Secret length: ${#secret}"
          fi
