name: Test Secret Usage

on:
  workflow_dispatch:  # manual trigger

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Check secret is set
        run: |
          if [ -z "${{ secrets.QA_PASSWORD }}" ]; then
            echo "Secret MY_SECRET is missing or empty."
            exit 1
          else
            echo "Secret MY_SECRET is set!"
          fi

      - name: Use secret in a command (example)
        run: |
          # Example: just print the length of the secret to confirm it has content
          secret_length=${#{{ secrets.QA_PASSWORD }}}
          echo "Secret length is: $secret_length"

          # Replace below with your actual command that uses the secret
          # some-cli-tool --token "${{ secrets.QA_PASSWORD }}" --do-something
